- name: Install apache2
  apt:
    name: apache2
    state: present
  become: true

- name: Install vim
  apt:
    name: vim
    state: present
  become: true

- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present
  become: true

- name: Install pxelinux
  apt:
    name: pxelinux
    state: present
  become: true

- name: Setup MOTD
  copy:
    src: motd
    dest: /etc/motd
  become: true

- name: Create pxelinux directory
  file:
    path: /tftpboot/pxelinux.cfg
    state: directory
  become: true

- name: Copy default pxe to directory
  copy:
    src: default
    dest: /tftpboot/pxelinux.cfg/default
  become: true

- name: Check that isos and directories exist
  debug:
    msg: "{{ item.0 }}{{ item.1 }}"
  with_together:
    - "{{ os_directories }}"
    - "{{ iso_file  }}"


#- name: Download iso
#  command: "mkdir -p {{ item.0 }} && wget {{ item.3 }}"
#  when: {{ item.0 }}{{ item.1 }} is not exists
#  with_together:
#    - {{ os_directories }}
#    - {{ iso_file  }}
#    - {{ iso_download_location }}
