---
- name: Template the systemd service file
  become: true
  ansible.builtin.template:
    src: loki.service.j2
    dest: /etc/systemd/system/loki.service
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd

- name: Enable loki
  become: true
  ansible.builtin.systemd:
    name: loki
    enabled: true
    state: started
