---
# Single node loki deployment - meant to be stupid simple and not redundant

# Loki Version specific details
loki_version: 2.9.4
loki_platform: linux
loki_architecture: arm64
loki_zip_sha: "sha256:92d1ea859044a9fc8d5916cb36a464545fec7bd70a7471c65cd21cc0f1834493"

loki_user: "loki"
loki_install_directory: "/opt/loki"

# Global Loki Configs
loki_auth_enabled: false

# Loki server configuration
loki_server_http_listen_post: 3100
loki_server_grpc_listen_post: 9096

# Loki ingester configuration
loki_ingester_lifecycler_address: 127.0.0.1
loki_ingester_lifecycler_ring_kvstore_store: "inmemory"
loki_ingester_lifecycler_ring_replication_factor: 1
loki_ingester_chunk_idle_period: "15m"
loki_ingester_chunk_retain_period: "30s"
loki_ingester_max_transfer_retries: 0

# Loki schema configuration
loki_schema_config_configs_from: "2020-10-24"
loki_schema_config_configs_store: "boltdb-shipper"
loki_schema_config_object_store: "filesystem"
loki_schema_config_schema: "v11"
loki_schema_config_index_prefix: "index_"
loki_schema_config_index_period: "24h"

# Loki storage configuration
loki_storage_config_boltdb_shipper_active_index_directory: "/opt/loki/index"
loki_storage_config_boltdb_shipper_cache_location: "/opt/loki/index_cache"
loki_storage_config_boltdb_shipper_shared_store: "filesystem"
loki_storage_config_filesystem_directory: "/opt/loki/chunks"

# Loki limits configuration
loki_limits_config_enforce_metric_name: false
loki_limits_config_reject_old_samples: true
loki_limits_config_reject_old_samples_max_age: "164h"

# Loki chunks configuration
loki_chunk_store_config_max_look_back_period: "0s"

# Loki table manager configuration
loki_table_manager_retention_deletes_enable: false
loki_table_manager_retention_period: "0s"

# Loki compactor configuration
loki_compactor_working_directory: "/opt/loki/compactor"
loki_compactor_shared_store: "filesystem"
