---
- name: Clone Vundle files
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "/home/{{item}}/.vim/bundle/Vundle.vim"
    version: 8db3bcb5921103f0eb6de361c8b25cc03cb350b5
  with_items: "{{users}}"

  # https://stackoverflow.com/questions/33672491/how-to-use-ansible-to-provision-vim-vundle-plugin
- name: Install Vundle packages
  shell: vim -E -s -c "source ~/.vimrc" -c PluginInstall -c qa
  ignore_errors: yes