---
- name: Create user
  user:
    name: "{{current_user}}"
    group: "users"
    groups: "sudo"
    shell: "/bin/bash"
  with_items: "{{users}}"

- name: Create a users .ssh directory
  sudo: True
  file:
    path: "/home/{{current_user}}/.ssh"
    state: directory
    mode: 0700
    owner: "{{current_user}}"
    group: "users"
  with_items: "{{users}}"

- name: Add user public keys from GitHub
  get_url:
    url: "https://github.com/{{current_user}}.keys"
    dest: "/home/{{current_user}}/.ssh/authorized_keys"
    mode: '0600'
  with_items: "{{users}}"