---
- name: "Install ceph-osd (1/3)"
  apt:
    name: ceph-osd=15.2.14-0ubuntu0.20.04.1
    state: present

- name: "Wipe /dev/sda3 partition (2/3)"
  shell: "wipefs -a /dev/sda3"

- name: "zap the /dev/sda3 partition (3/3)"
  shell: "ceph-volume lvm zap /dev/sda3"
