---
- name: "Apply Namespace Manifest (1/2)"
  shell: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.10.2/manifests/namespace.yaml

- name: "Apply MetalLb Manifest (2/2)"
  shell: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.10.2/manifests/metallb.yaml

- name: "Copy MetalLB Default ConfigMap to Node (3/4)"
  template:
    src: default-ip-range-configmap.yaml
    dest: /tmp/default-ip-range-configmap.yaml
    force: yes

- name: "Apply MetalLB Default ConfigMap (4/4)"
  shell: kubectl apply -f default-ip-range-configmap.yaml
