---
- name: Download file from the Internet
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/grafana/mimir/releases/download/mimir-{{ mimir_version}}/mimir-{{ mimir_platform }}-{{ mimir_architecture }}"
    dest: "{{ mimir_install_directory }}/mimir"
    checksum: "{{ mimir_binary_sha }}"
    owner: "{{ mimir_user }}"
    group: "{{ mimir_user }}"
    mode: '0755'

- name: Ensure file ownership and permissions
  become: true
  ansible.builtin.file:
    path: "{{ mimir_install_directory }}/mimir"
    owner: "{{ mimir_user }}"
    group: "{{ mimir_user }}"
    mode: '0755'
