---
- name: Template the systemd service file
  become: true
  ansible.builtin.template:
    src: mimir.service.j2
    dest: /etc/systemd/system/mimir.service
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd

- name: Enable mimir
  become: true
  ansible.builtin.systemd:
    name: mimir
    enabled: true
    state: started
